// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompositeLayer } from "./CompositeLayer";

/**
 * Several images placed freely on the canvas at once. Each monitor composites
 * every overlapping layer in `layers` order (index 0 = bottom, last = top);
 * uncovered regions render black. The canvas is the source of truth, exactly
 * like [`SpanProfile`] — `layers` just generalises its single rect to many.
 */
export type CompositeProfile = { 
/**
 * Bottom-to-top stacking order; the last layer wins where images overlap.
 */
layers: Array<CompositeLayer>, };
