// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendConfig } from "./BackendConfig";
import type { GeneralConfig } from "./GeneralConfig";
import type { LibraryConfig } from "./LibraryConfig";
import type { MonitorConfig } from "./MonitorConfig";
import type { Profile } from "./Profile";
import type { Schedule } from "./Schedule";

/**
 * Loaded from `$XDG_CONFIG_HOME/superpanels/config.toml`. All sections have
 * defaults, so a missing or minimal file is valid.
 */
export type Config = { general: GeneralConfig, backend: BackendConfig, library: LibraryConfig, monitor: Array<MonitorConfig>, profile: Array<Profile>, schedule: Array<Schedule>, 
/**
 * Master pause for all schedules; mirrored in the tray menu.
 */
schedules_paused: boolean, };
