// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorId } from "./MonitorId";
import type { Rect } from "./Rect";
import type { Rotation } from "./Rotation";

/**
 * Per-monitor crop and render parameters.
 */
export type CropSpec = { monitor_id: MonitorId, src_rect: Rect, dst_offset: [number, number], dst_size: [number, number], slice_dst_size: [number, number], rotation: Rotation, };
