// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `FitMode` survives only as a per-monitor scaling hint for `PerMonitor`
 * profiles. Span profiles describe placement entirely via `ImageRectMm`.
 */
export type FitMode = "fill" | "fit" | "stretch" | "center";
