// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralConfig = { 
/**
 * Profile to apply on daemon start, overriding the resumed last-active
 * profile from `resume-state.json`; `None` resumes (or does nothing).
 */
default_profile: string | null, autostart: boolean, notifications: string, theme: string, };
