// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralConfig = { 
/**
 * Profile to apply on daemon start when `state.toml` has no
 * `active_profile` recorded; `None` means do nothing.
 */
default_profile: string | null, autostart: boolean, notifications: string, theme: string, };
