// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRectMm } from "./ImageRectMm";
import type { MonitorPlacement } from "./MonitorPlacement";

/**
 * Per-image canvas snapshot inside a slideshow: the same placement + image
 * rect a profile persists at top level, applied only when this image is up.
 */
export type ImageOverride = { 
/**
 * Keys are `Monitor.stable_id` (or `name` fallback), matching
 * [`super::Profile::monitor_state`].
 */
monitor_state: { [key in string]: MonitorPlacement }, image_rect_mm: ImageRectMm, };
