// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageSource = { "type": "folder", path: string, recursive: boolean, } | { "type": "image", path: string, };
