// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageSet = { "type": "folder", path: string, recursive: boolean, } | { "type": "playlist", paths: Array<string>, };
