// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSource } from "./ImageSource";

/**
 * Mixed slideshow pool: any number of live folders and hand-picked images.
 * Deserialization also accepts the pre-1.0 single-variant forms
 * (`type = "folder"` / `type = "playlist"`) and lifts them into `sources`.
 */
export type ImageSet = { sources: Array<ImageSource>, };
