// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image rectangle in canvas mm-space — the source of truth for span apply.
 */
export type ImageRectMm = { x_mm: number, y_mm: number, w_mm: number, h_mm: number, };
