// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpcError = { "kind": "Daemon", "message": string } | { "kind": "Config", "message": string } | { "kind": "Detect", "message": string } | { "kind": "Layout", "message": string } | { "kind": "Backend", "message": string } | { "kind": "Image", "message": string } | { "kind": "Library", "message": string } | { "kind": "InvalidArgument", "message": string } | { "kind": "Internal", "message": string };
