// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Decimal degrees lat/long for sunset/sunrise scheduling
 * (`docs/spec/09-profiles-schedules.md` §9.3).
 */
export type LatLong = { lat: number, lon: number, };
