// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter forwarded to `library_list`. Mirrors `superpanels_core::LibraryFilter`
 * but is defined in the GUI crate so `ts-rs` can export it for the frontend.
 */
export type LibraryFilter = { tag?: string, min_width?: number, min_height?: number, aspect_min?: number, aspect_max?: number, offset?: number, limit?: number, };
