// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime monitor id. Newtype so `fn apply(profile: ProfileId, monitor: MonitorId)`
 * can't be called with arguments swapped.
 */
export type MonitorId = number;
