// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorId } from "./MonitorId";
import type { Rotation } from "./Rotation";

/**
 * A physical display normalised into Superpanels' internal model.
 */
export type Monitor = { 
/**
 * Runtime-only; never persisted — use [`MonitorRef`] for that.
 */
id: MonitorId, name: string, 
/**
 * KDE per-output UUID, or hash of EDID `manufacturer + model + serial`.
 */
stable_id: string | null, 
/**
 * Top-left in logical desktop pixels (post-scale).
 */
position: [number, number], 
/**
 * Native-orientation pixel dimensions.
 */
resolution: [number, number], 
/**
 * Native-orientation mm. Sourced from `[[monitor]]` config — detectors
 * don't expose this. `None` until the user fills it in; bezel math
 * returns `LayoutError::PhysicalSizeMissing` until then.
 */
physical_size_mm: [number, number] | null, scale: number, rotation: Rotation, refresh_hz: number | null, 
/**
 * Post-rotation, derived from `resolution` and `physical_size_mm`.
 */
ppi: number | null, };
