// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `[[monitor]]` block. At least one of `stable_id` / `name` must be set;
 * matching tries `stable_id` first, then falls back to `name`.
 */
export type MonitorConfig = {
  stable_id?: string | null;
  name?: string | null;
  /**
   * `[w, h]` in millimetres. Fractional values accepted.
   */
  physical_mm: [number, number];
};
