// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rotation } from './Rotation';

/**
 * Authored monitor canvas state lifted out of the transient
 * `MonitorOverride` from `ui/src/lib/stores/canvas-view.svelte.ts`. The
 * `(x_mm, y_mm)` are the monitor's top-left in physical millimetres on the
 * authored canvas; gaps between monitors fall out of the placements.
 */
export type MonitorPlacement = { x_mm: number; y_mm: number; rotation: Rotation };
