// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent monitor reference. All persisted data —
 * per-monitor config, profile assignments — keys on this rather than the
 * runtime [`MonitorId`]. `name` is the fallback when the detector can't
 * supply a `stable_id`.
 */
export type MonitorRef = { stable_id: string, name: string, };
