// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitMode } from "./FitMode";
import type { PerMonitorAssignment } from "./PerMonitorAssignment";

export type PerMonitorProfile = { assignments: Array<PerMonitorAssignment>, fit: FitMode, };
