// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorRef } from "./MonitorRef";

export type PerMonitorAssignment = { monitor: MonitorRef, path: string, };
