// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRectMm } from "./ImageRectMm";

export type PreviewArgs = { image: string, image_rect_mm: ImageRectMm | null, };
