// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewArgs = { image: string, offset_px: [number, number], bezel_h_mm: number, bezel_v_mm: number, fit: string, };
