// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerMonitorProfile } from "./PerMonitorProfile";
import type { SpanProfile } from "./SpanProfile";

/**
 * `body` of a [`super::Profile`]. The `body`/`source` two-enum split makes
 * "per-monitor + slideshow" unrepresentable.
 */
export type ProfileBody = { "type": "span" } & SpanProfile | { "type": "per_monitor" } & PerMonitorProfile;
