// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisableReason } from "./DisableReason";

export type ProfileValidity = { "kind": "ok" } | { "kind": "disabled", reasons: Array<DisableReason>, };
