// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wraps `chrono::DateTime<Utc>` so it round-trips through TOML's
 * RFC-3339 string form. The default is "now"; `serde` uses chrono's
 * existing impls.
 */
export type ProfileTimestamp = string;
