// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlideshowProfile } from "./SlideshowProfile";
import type { StandardProfile } from "./StandardProfile";

/**
 * `body` of a [`super::Profile`]. Each variant is a distinct wallpaper mode.
 */
export type ProfileBody = { "type": "standard" } & StandardProfile | { "type": "slideshow" } & SlideshowProfile;
