// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Curated 12-swatch palette used for tray pills, manager rows, and dialog
 * pickers. Values map 1:1 to the mockup's `SWATCHES` list.
 */
export type ProfileColour =
  | 'slate'
  | 'stone'
  | 'red'
  | 'orange'
  | 'amber'
  | 'yellow'
  | 'lime'
  | 'emerald'
  | 'teal'
  | 'sky'
  | 'indigo'
  | 'violet';
