// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widths of the window's resize grab regions, in logical pixels. Exported so
 * the frontend's cursor geometry can't drift from the backend's hit test.
 */
export type ResizeBands = { edge: number, corner: number, };
