// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Trigger } from './Trigger';

/**
 * Top-level schedule rule. References a profile by name; bound at fire time.
 */
export type Schedule = {
  /**
   * Optional human-readable label (for the manager UI). `None` falls back
   * to a derived summary like "Daily 18:00 → dark".
   */
  display_name?: string | null;
  profile: string;
  trigger: Trigger;
  enabled: boolean;
};
