// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SlideshowSort =
  | 'shuffle'
  | 'alphabetical'
  | 'date_asc'
  | 'date_desc'
  | 'last_shown_asc';
