// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRectMm } from "./ImageRectMm";
import type { SlideshowSource } from "./SlideshowSource";

export type SlideshowProfile = { source: SlideshowSource, 
/**
 * The image's rectangle in canvas mm-space, applied under `uniform_layout`
 * (and as the baseline for the live image): monitors crop whatever they
 * overlap with this rectangle.
 */
image_rect_mm: ImageRectMm, };
