// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitMode } from "./FitMode";
import type { SpanSource } from "./SpanSource";

export type SpanProfile = { source: SpanSource, fit: FitMode, 
/**
 * Image-position offset in canvas px.
 */
offset: [number, number], 
/**
 * Explicit image rectangle in canvas px (`docs/spec/12-gui.md` §12.3).
 */
image_size_px?: [number, number] | null, };
