// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageRectMm } from "./ImageRectMm";
import type { SpanSource } from "./SpanSource";

export type SpanProfile = { source: SpanSource, 
/**
 * The image's rectangle in canvas mm-space — the canvas is the source
 * of truth: monitors crop whatever they overlap with this rectangle.
 */
image_rect_mm: ImageRectMm, };
