// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StandardLayer } from "./StandardLayer";

/**
 * One or more images placed freely on the canvas. Each monitor composites
 * every overlapping layer in `layers` order (index 0 = bottom, last = top);
 * uncovered regions render black. The canvas is the source of truth. A single
 * image is just a one-layer Standard.
 */
export type StandardProfile = { 
/**
 * Bottom-to-top stacking order; the last layer wins where images overlap.
 */
layers: Array<StandardLayer>, };
