// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque hash over (sorted `stable_id`s ∥ rotations) for the connected set
 * at apply time. Profile authoring captures it; topology comparison is by
 * equality. Pixel resolution is deliberately excluded — a resolution change
 * rescales gracefully, only orientation flips invalidate.
 */
export type TopologyFingerprint = string;
