// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Trigger half of a [`Schedule`]. Promoted out of profile bodies so a
 * rule can reference any profile by name.
 */
export type Trigger = { "type": "daily", hour: number, minute: number, } | { "type": "sunset", offset_minutes: number, } | { "type": "sunrise", offset_minutes: number, } | { "type": "cron", expr: string, };
